GET http://localhost:8080/api/models

###
GET http://localhost:8080/api/auth/token

### GET List Model Views
GET https://developer.api.autodesk.com/modelderivative/v2/designdata/dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6YTVzZWV2dmZkNmVyMGhnZ2VzaWJ1cXB4cnZkNW1nYTJrZzI1enowcWVmZnd1ZG5mLWJhc2ljLWFwcC9Ib3RlbCUyMEIxJTIwTW9kZWxvJTIwTmF2aXMubndk/metadata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlhrUFpfSmhoXzlTYzNZS01oRERBZFBWeFowOF9SUzI1NiIsInBpLmF0bSI6ImFzc2MifQ.eyJzY29wZSI6WyJ2aWV3YWJsZXM6cmVhZCIsImRhdGE6cmVhZCJdLCJjbGllbnRfaWQiOiJBNXNlRXZ2ZkQ2RXIwaEdnRXNpYnVxcHhydkQ1TUdhMmtnMjV6ejBRRUZGd1VETmYiLCJpc3MiOiJodHRwczovL2RldmVsb3Blci5hcGkuYXV0b2Rlc2suY29tIiwiYXVkIjoiaHR0cHM6Ly9hdXRvZGVzay5jb20iLCJqdGkiOiJDeGZWdU1DeXJ2SXNSUDdWN2U4T3JkbFpxN2U3NHE5Q0dlNHFHNFBEQUdiZjRBQ1lGMW9WM2pGdk5aSmg0NlZPIiwiZXhwIjoxNzM2MzUzNDI1fQ.L4h941oTJkV2OJaFofxneIeSJcxpP6zvyLE5LtT5dfrRtNn6xdZnfL4GHJpyqUYXW_fM1zc0J7qVaI8JrXnEVqfwsmJVt5pAg_EMVrPG2kIUzHtZzZRT4JHMVtgSzH3J8mc_DV651aMe0TxQg0FQQDfWVpyH5sLNpVqN4zSmJiuOUEEk8UAwl_XezIac9MwWzc6b2krYwiNUE6sqEubNZzYC5kE04EIUBwe66wRohwU1uMVogX_Lpz9F827BaYHBfOad0yIE66gFQ_Fe01tCpdAYGxQmY5i4_IAeqWVIovofrlz1R17WDWJz0TXOgCVodwgmEIcSXqV92PJRsVXKhA

### GET All properties
GET https://developer.api.autodesk.com/modelderivative/v2/designdata/dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6YTVzZWV2dmZkNmVyMGhnZ2VzaWJ1cXB4cnZkNW1nYTJrZzI1enowcWVmZnd1ZG5mLWJhc2ljLWFwcC9Ib3RlbCUyMEIxJTIwTW9kZWxvJTIwTmF2aXMubndk/metadata/16623373-c5f0-43f4-81dd-2ed32925d1b9/properties?forceget=true
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlhrUFpfSmhoXzlTYzNZS01oRERBZFBWeFowOF9SUzI1NiIsInBpLmF0bSI6ImFzc2MifQ.eyJzY29wZSI6WyJ2aWV3YWJsZXM6cmVhZCIsImRhdGE6cmVhZCJdLCJjbGllbnRfaWQiOiJBNXNlRXZ2ZkQ2RXIwaEdnRXNpYnVxcHhydkQ1TUdhMmtnMjV6ejBRRUZGd1VETmYiLCJpc3MiOiJodHRwczovL2RldmVsb3Blci5hcGkuYXV0b2Rlc2suY29tIiwiYXVkIjoiaHR0cHM6Ly9hdXRvZGVzay5jb20iLCJqdGkiOiJDeGZWdU1DeXJ2SXNSUDdWN2U4T3JkbFpxN2U3NHE5Q0dlNHFHNFBEQUdiZjRBQ1lGMW9WM2pGdk5aSmg0NlZPIiwiZXhwIjoxNzM2MzUzNDI1fQ.L4h941oTJkV2OJaFofxneIeSJcxpP6zvyLE5LtT5dfrRtNn6xdZnfL4GHJpyqUYXW_fM1zc0J7qVaI8JrXnEVqfwsmJVt5pAg_EMVrPG2kIUzHtZzZRT4JHMVtgSzH3J8mc_DV651aMe0TxQg0FQQDfWVpyH5sLNpVqN4zSmJiuOUEEk8UAwl_XezIac9MwWzc6b2krYwiNUE6sqEubNZzYC5kE04EIUBwe66wRohwU1uMVogX_Lpz9F827BaYHBfOad0yIE66gFQ_Fe01tCpdAYGxQmY5i4_IAeqWVIovofrlz1R17WDWJz0TXOgCVodwgmEIcSXqV92PJRsVXKhA